language: python
python:
- '3.3'
- '3.4'
- '3.5'
install: pip install -r requirements.txt
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script: py.test
deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  user: andrea.raith
  password:
    secure: OfFADS4sQPcbqcSd3md25Nj1JMxQ+mxuuEOnvk78JNr9Pc4p5mS2MLJ8g4zmv/6CQGzxryCixIGMeUy7joYM29eJcV/J+jxXSNI9jtJ+/3f9PPfREJAZgXgVUuvP0k5hI/Iobofybm5BziU5aoUnwnGah8VD2FB1IwztWLJp9Ew27bLpBXoRER+1SUFqM01Fog6oCsC6DDwI/cTP5CG/KsigD46JLe9aWs3IoDG1ybQuKmgNtCFusXS0gDmfSRMz91FpMLkOKYxqRR5vZGMz/fIkM9Xj1ZsodJtA3QLDq16AB0ANdEwUs5jmfcndZFIYD+HcodOg6Q84nPmgid5oqvn8nLeM4AU0dUpRcXbq87EBmWZTTkfV0RUCgR9pCek+UbumBut8BmyI0QM55At+B5ltSfIiNPD72A3cradv0MnTARCj/cGaEQqXPAlxH5fhAGaHZ4hxBvH6l8qZJP10EQvQ7EQq5V8P80xcp/f1eC9QqAeFX81/D7AVn/+pZ7iNlSBoMpUIcF55RdkZ2MN4KZ3q7iCrBv9ONRNzOd5kiPK0iCAOfVJopqJO/tXVVgaPbO1AYNl12bFaBkBxTu0lcRQJqcOy02XCoWZpkbfJggJ487Z6XD8k2SCjGQQCUiEUpgknIQbNnCxlbCDUVmhv+46ZBGWFbK9sJzndn3A2TZw=
  on:
    tags: true
    all_branches: true
